version: '3.7'

services:
    web:
      build: ./backend
      command: python manage.py runserver 0.0.0.0:8000
      #command: gunicorn vuelosApi.wsgi --reload --workers 5 --threads=8 --bind 0.0.0.0:8000 --timeout 300

      ports:
        - "8000:8000"

