# Generated by Django 4.1 on 2023-02-25 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opera', models.CharField(max_length=100)),
                ('tipovuelo', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('siglaDes', models.CharField(max_length=100)),
                ('siglaOri', models.CharField(max_length=100)),
                ('fecha_vuelo', models.DateTimeField()),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
