# Generated by Django 4.1 on 2023-02-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='siglaDes',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='siglaOri',
        ),
    ]
