# Generated by Django 4.1 on 2023-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_remove_consultas_siglades_remove_consultas_siglaori'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='vuelo_i',
            field=models.CharField(default=222, max_length=5),
            preserve_default=False,
        ),
    ]
