# Generated by Django 4.1 on 2023-02-26 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0004_rename_mes_consultas_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='fecha_consulta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
